Add mychannels plugin
UsergeTeam/Userge-Plugins pull request #220
Opened 2021-08-19 19:02 UTC by pseudokawaii

Users will be able to list all the channels and groups they created or have administrative privileges on.

2021-08-19 19:02 UTC, pep8speaks commented
@pseudokawaii, Thanks for opening this PR.

* In the file [`plugins/mychannels.py`](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py):

> [Line 4:1](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L4): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 15:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 100 characters)
> [Line 17:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L17): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 100 characters)
> [Line 24:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L24): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (183 > 100 characters)
> [Line 26:1](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L26): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 36:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 100 characters)
> [Line 38:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 100 characters)
> [Line 40:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 100 characters)
> [Line 49:101](https://github.com/UsergeTeam/Userge-Plugins/blob/b878cbb67c11ebfd611629daecdd2af48eebe85e/plugins/mychannels.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (195 > 100 characters)

2021-08-20 08:42 UTC, Krishna-Singhal commented
Nice, try combining both commands into 1 command.

2021-09-02 11:36 UTC, pseudokawaii commented
@Krishna-Singhal how about now?

2021-09-02 11:46 UTC, Krishna-Singhal requested changes

2021-09-02 11:46 UTC, Krishna-Singhal commented on plugins/domain.py
> +        status = "administrator"
here also

2021-09-02 11:46 UTC, Krishna-Singhal commented on plugins/domain.py
> +    if "-c" in m.input_str:
use
```python
m.flags
```
 instead of 
```python
m.input_str
```

2021-09-02 11:46 UTC, Krishna-Singhal requested changes

2021-09-02 11:46 UTC, Krishna-Singhal commented on plugins/domain.py
> +    elif "-a" in m.input_str:
here also

2021-09-02 11:57 UTC, pseudokawaii commented on plugins/domain.py
> +    elif "-a" in m.input_str:
@Krishna-Singhal done.

2021-09-02 15:47 UTC, Krishna-Singhal approved these changes

2021-09-03 17:14 UTC, rking32 commented
@pseudokawaii Thanks for this plugin :)

2021-09-03 17:14 UTC, merged